### ISSUE TITLE
Xantrex with RJ12 Port

### ISSUE THREAD

**Issue by pmulkins** [clockbrain/xantrex#2]
Hey,

Thank you for figuring this out! I have a newer model (Freedom XC 2000) with only a RJ12 port for the remote. Do you think the communication would be similar? 

Thanks!

**Comment by clockbrain** [comment]
Hi @pmulkins Sorry I don't know that model. I couldn't find anything online that stated whether that RJ12 port connects with direct wiring or some sort of serial communications. The best suggestion I could find was to take the remote apart (gently) and see if you could tell if it has serial comms chips on the circuit board. Even if it is serial comms it is unlikely the protocol would be the same as the model I have since the remote for your unit has different functions.

**Comment by pmulkins** [comment]
Understood. Darn. Ok, then I leave it as is for now. Hopefully, someone can reverse engineer the Bluetooth commands via the APK as the remote also adds Bluetooth functionality. 
Thank you for replying!
